/** ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : usb_msc_config.h
**     Project     : Splinter bringup
**     Processor   : MK65FX1M0VMI18
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-08-18, 16:51, # CodeGen: 71
**     Abstract    :
**          This component encapsulates the Universal Serial Bus (USB)
**          module in the device mode according to specification 2.0. 
**          It allows design variable configurations, interfaces and endpoints.
**     Settings    :
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file usb_msc_config.h                                                  
** @version 01.00
** @brief
**          This component encapsulates the Universal Serial Bus (USB)
**          module in the device mode according to specification 2.0. 
**          It allows design variable configurations, interfaces and endpoints.
*/         
/*!
**  @addtogroup usb_msc_config_module usb_msc_config module documentation
**  @{
*/         
#ifndef __usb_msc_config__
#define __usb_msc_config__

#define IMPLEMENTING_DISK_DRIVE        (0)

#define MSD_RECV_MAX_TRANS_LENGTH      (65536)
#define MSD_SEND_MAX_TRANS_LENGTH      (65536)

#define MAX_MSC_DEVICE                 (1)
#define MAX_MSC_SUPPORTED_INTERFACES   (0)

#endif /* __usb_msc_config__ */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
