/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : hid1.h
**     Project     : Splinter bringup
**     Processor   : MK65FX1M0VMI18
**     Component   : fsl_usb_device_hid_class
**     Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.2.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-08-07, 14:52, # CodeGen: 10
**     Abstract    :
**
**     Settings    :
**          Component name                                 : hid1
**          fsl_usb_descriptor component link              : usbDsc1
**          Update fsl_usb_descriptor component            : 
**          Generated code common settings                 : 
**            Mark all descriptors as const                : yes
**          HID class setting                              : 0x03
**            Subclass code                                : 0x00 No Subclass
**            Protocol code                                : 0x02 Mouse
**          HID descriptor                                 : 
**            HID Class specification release number       : 1.11
**            Country code                                 : 0x00 Not Supported
**            Class descriptor list                        : 1
**              HID class descriptor 0                     : 
**                Descriptor type                          : HID_REPORT
**                Descriptor size                          : 50
**                Descriptor name                          : hid1_MouseReportDescriptor
**          Report descriptor                              : 
**            Report descriptor templates                  : 
**              Configure as mouse                         : 
**              Configure as keyboard                      : 
**            Descriptor name                              : hid1_MouseReportDescriptor
**            ShowItemData                                 : no
**            Report Descriptor Size                       : 50
**            Input Report Size                            : 3
**            Output Report Size                           : 0
**            Feature Report Size                          : 0
**            Report descriptor Item List                  : 26
**              Item 0                                     : Usage Page
**                Usage Page                               : Generic Desktop Controls
**              Item 1                                     : Usage
**                Usage Page                               : Generic Desktop Controls
**                Usage                                    : Mouse
**              Item 2                                     : Collection
**                Collection type                          : Application
**              Item 3                                     : Usage
**                Usage Page                               : Generic Desktop Controls
**                Usage                                    : Pointer
**              Item 4                                     : Collection
**                Collection type                          : Physical
**              Item 5                                     : Usage Page
**                Usage Page                               : Button
**              Item 6                                     : Usage Minimum
**                Usage Page                               : Button
**                Usage Minimum                            : Button 1 (primary/trigger)
**              Item 7                                     : Usage Maximum
**                Usage Page                               : Button
**                Usage Maximum                            : Button 3 (tertiary)
**              Item 8                                     : Logical Minimum
**                Logical minimum Value                    : 0
**              Item 9                                     : Logical Maximum
**                Logical maximum Value                    : 1
**              Item 10                                    : Report Count
**                Report Count                             : 3
**              Item 11                                    : Report Size
**                Report Size                              : 1
**              Item 12                                    : Input
**                Report Item properties                   : 3
**                  Item 0                                 : 
**                    Data Field Name                      : hid1_Button_1
**                    Data Field Offset                    : 0
**                    Data Field Size                      : 1
**                    Data Field Usage Page                : Button
**                    Data Field Usage                     : Not defined
**                    Data Field Logical Minimum           : 0
**                    Data Field Logical Maximum           : 1
**                  Item 1                                 : 
**                    Data Field Name                      : hid1_Button_2
**                    Data Field Offset                    : 1
**                    Data Field Size                      : 1
**                    Data Field Usage Page                : Button
**                    Data Field Usage                     : Not defined
**                    Data Field Logical Minimum           : 0
**                    Data Field Logical Maximum           : 1
**                  Item 2                                 : 
**                    Data Field Name                      : hid1_Button_3
**                    Data Field Offset                    : 2
**                    Data Field Size                      : 1
**                    Data Field Usage Page                : Button
**                    Data Field Usage                     : Not defined
**                    Data Field Logical Minimum           : 0
**                    Data Field Logical Maximum           : 1
**                Type                                     : Data
**                Data Sense                               : Variable
**                Data Relation                            : Absolute
**                Data Wrapping                            : No Wrap
**                Data Linearity                           : Linear
**                Default State                            : Preferred State
**                Null Position                            : No Null Position
**                Format                                   : Bit Field
**              Item 13                                    : Report Count
**                Report Count                             : 1
**              Item 14                                    : Report Size
**                Report Size                              : 5
**              Item 15                                    : Input
**                Report Item properties                   : 1
**                  Item 0                                 : 
**                    Data Field Name                      : hid1_Reserved_1
**                    Data Field Offset                    : 3
**                    Data Field Size                      : 5
**                    Data Field Usage Page                : Button
**                    Data Field Usage                     : Not defined
**                    Data Field Logical Minimum           : 0
**                    Data Field Logical Maximum           : 1
**                Type                                     : Constant
**                Data Sense                               : Array
**                Data Relation                            : Absolute
**                Data Wrapping                            : No Wrap
**                Data Linearity                           : Linear
**                Default State                            : Preferred State
**                Null Position                            : No Null Position
**                Format                                   : Bit Field
**              Item 16                                    : Usage Page
**                Usage Page                               : Generic Desktop Controls
**              Item 17                                    : Usage
**                Usage Page                               : Generic Desktop Controls
**                Usage                                    : X
**              Item 18                                    : Usage
**                Usage Page                               : Generic Desktop Controls
**                Usage                                    : Y
**              Item 19                                    : Logical Minimum
**                Logical minimum Value                    : -127
**              Item 20                                    : Logical Maximum
**                Logical maximum Value                    : 127
**              Item 21                                    : Report Size
**                Report Size                              : 8
**              Item 22                                    : Report Count
**                Report Count                             : 2
**              Item 23                                    : Input
**                Report Item properties                   : 2
**                  Item 0                                 : 
**                    Data Field Name                      : hid1_X
**                    Data Field Offset                    : 8
**                    Data Field Size                      : 8
**                    Data Field Usage Page                : Generic Desktop Controls
**                    Data Field Usage                     : Y
**                    Data Field Logical Minimum           : -127
**                    Data Field Logical Maximum           : 127
**                  Item 1                                 : 
**                    Data Field Name                      : hid1_Y
**                    Data Field Offset                    : 16
**                    Data Field Size                      : 8
**                    Data Field Usage Page                : Generic Desktop Controls
**                    Data Field Usage                     : Y
**                    Data Field Logical Minimum           : -127
**                    Data Field Logical Maximum           : 127
**                Type                                     : Data
**                Data Sense                               : Variable
**                Data Relation                            : Relative
**                Data Wrapping                            : No Wrap
**                Data Linearity                           : Linear
**                Default State                            : Preferred State
**                Null Position                            : No Null Position
**                Format                                   : Bit Field
**              Item 24                                    : Collection End
**              Item 25                                    : Collection End
**          Optional class descriptor                      : 0
**          Initialization                                 : Enabled
**            HID device handler name                      : hid1_HidHandle
**            HID configuration structure name             : hid1_HidConfigStructure
**            USB HID demo                                 : Disabled
**            Callback user parameters                     : 
**              Application callback                       : 
**                application_callback arg                 : NULL
**                External declaration of parameter        : 
**              Vendor request callback                    : 
**                vendor_req_callback_arg                  : NULL
**                External declaration of parameter        : 
**              Class specific callback                    : 
**                class_specific_callback arg              : NULL
**                External declaration of parameter        : 
**            Auto initialization                          : Enabled
**     Contents    :
**         USB_Class_HID_Init      - usb_status USB_Class_HID_Init(uint8_t controller_id, hid_config_struct_t *...
**         USB_Class_HID_Deinit    - usb_status USB_Class_HID_Deinit(hid_handle_t handle);
**         USB_Class_HID_Recv_Data - usb_status USB_Class_HID_Recv_Data(hid_handle_t handle, uint8_t ep_num,...
**         USB_Class_HID_Send_Data - usb_status USB_Class_HID_Send_Data(hid_handle_t handle, uint8_t ep_num,...
**         USB_Class_HID_Cancel    - usb_status USB_Class_HID_Cancel(hid_handle_t handle, uint8_t ep_num, uint8_t...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file hid1.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup hid1_module hid1 module documentation
**  @{
*/         

#ifndef __hid1_H
#define __hid1_H

/* MODULE hid1. */

/* Include inherited components */
#include "usbDsc1.h"
#include "usb.h"
#include "usb_device_stack_interface.h"
#include "usb_class_hid.h"

/* Input report 1 data buffer size */
#define hid1_InputReport_ID_1_Size 0x03
/* Input report 1 data buffer prototype  */
typedef uint8_t hid1_InputReport_ID_1[hid1_InputReport_ID_1_Size];
/* Input report 1 data buffer initialization macro */
#define hid1_InitInputReport_ID_1(ReportName__) { \
  ReportName__[0]=0x00; \
  ReportName__[1]=0x00; \
  ReportName__[2]=0x00; \
};

#define hid1_Button_1_SetVal(RepDescr_,Val_)                (RepDescr_)[0] = (uint8_t)(((RepDescr_)[0] & ((uint8_t)0xFE)) | ((Val_) << 0x00))
#define hid1_Button_2_SetVal(RepDescr_,Val_)                (RepDescr_)[0] = (uint8_t)(((RepDescr_)[0] & ((uint8_t)0xFD)) | ((Val_) << 0x01))
#define hid1_Button_3_SetVal(RepDescr_,Val_)                (RepDescr_)[0] = (uint8_t)(((RepDescr_)[0] & ((uint8_t)0xFB)) | ((Val_) << 0x02))
#define hid1_Reserved_1_SetVal(RepDescr_,Val_)              (RepDescr_)[0] = (uint8_t)(((RepDescr_)[0] & ((uint8_t)0x07)) | ((Val_) << 0x03))
#define hid1_X_SetVal(RepDescr_,Val_)                       (RepDescr_)[1] = (uint8_t)(Val_)
#define hid1_Y_SetVal(RepDescr_,Val_)                       (RepDescr_)[2] = (uint8_t)(Val_)

/* USB HID device class handle */  
extern hid_handle_t hid1_HidHandle;
/* USB HID class configuration structure */
extern hid_config_struct_t hid1_HidConfigStructure;

/* END hid1. */

#endif
/* ifndef __hid1 */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
